# Generated by Django 6.0.1 on 2026-03-05 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('MC', 'Mission Capable'), ('GND', 'Grounded'), ('MAINT', 'In Maintenance')], default='MC', max_length=5)),
                ('airframe_hours', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=50, unique=True)),
                ('rank', models.CharField(max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_mission_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_id', models.CharField(max_length=20, unique=True)),
                ('scheduled_at', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='sorties.aircraft')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='sorties.pilot')),
            ],
        ),
    ]
