# Generated by Django 6.0.1 on 2026-03-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='last_formation_flight',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pilot',
            name='last_gh_flight',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pilot',
            name='last_if_flight',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pilot',
            name='last_night_flight',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
